# WordPress Plugin Development - WordPress container image 
FROM wordpress:latest
MAINTAINER gregoryfoster <fostgr@consumer.org>

ENV WORDPRESS_DB_NAME=wp_consunion \
    WORDPRESS_DB_USER=wp_consunion \
    WORDPRESS_DB_PASSWORD=123456 \
    WORDPRESS_TABLE_PREFIX='wp_'

