# WordPress Plugin Development - MySQL container image 
FROM mysql:5.5
MAINTAINER gregoryfoster <fostgr@consumer.org>

ENV MYSQL_ROOT_PASSWORD=123456 \
    MYSQL_DATABASE=wp_consunion \
    MYSQL_USER=wp_consunion \
    MYSQL_PASSWORD=123456
