docker create \
  --name dwp-mysql \
  --env=MYSQL_ROOT_PASSWORD=$DWP_MYSQL_ROOT_PASSWORD \
  --env=MYSQL_DATABASE=$DWP_MYSQL_DATABASE \
  --env=MYSQL_USER=$DWP_MYSQL_USER \
  --env=MYSQL_PASSWORD=$DWP_MYSQL_USER_PASSWORD \
  mysql:$DWP_MYSQL_VERSION_TAG
